__author__ = 'Naiii'

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""

limit = 4000000

fib = [1, 2]
x = 0
while x < limit:
    x = (fib[-1] + fib[-2])
    if x > limit:  # w/out it would append one term bigger then 4 mil and then exit the loop
        break
    fib.append(x)

for numb in fib:
    if numb % 2 == 1:
        print("odd: " + str(numb))
        fib.remove(numb)
    else:
        print("even: " + str(numb))

for numb in fib:
    if numb % 2 == 1:
        print("odd: " + str(numb))
        fib.remove(numb)
    else:
        print("even: " + str(numb))

print(fib)
print(len(fib))

result = sum(fib)
print(result)